from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = ROOT / ".env"
EXAMPLE_FILE = ROOT / ".env.example"

DEFAULTS = {
    "DAKORA_API_KEY": "dk_proj_your_project_key",
    "DAKORA_TEMPLATE_ID": "faq_responder",
    "OPENAI_API_KEY": "sk-your-openai-key",
    "OPENAI_MODEL": "gpt-4o-mini",
}


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def prompt(key: str, default: str) -> str:
    try:
        entered = input(f"{key} [{default}]: ").strip()
    except KeyboardInterrupt:
        print("\nAborted.")
        sys.exit(1)
    return entered or default


def main() -> int:
    if not EXAMPLE_FILE.exists():
        print("Missing .env.example. Make sure you run this from the dakora-examples folder.")
        return 1

    existing = parse_env_file(ENV_FILE)
    print("Filling .env with your Dakora and provider keys.")
    print("Press Enter to keep the shown default.")

    values: dict[str, str] = {}
    for key, default in DEFAULTS.items():
        current_default = existing.get(key, default)
        values[key] = prompt(key, current_default)

    lines = [
        "# Generated by scripts/setup_env.py",
        "# Update these values as needed.",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())

    ENV_FILE.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {ENV_FILE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
